apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: app-scoring-binding
spec:
  params:
  - name: imageRepo
    value: "{{ $.Values.globex.registry.imageRepo }}"
  - name: manifestRepo
    value: "{{ $.Values.globex.git.manifestRepo }}"
  - name: manifestFile
    value: "{{ $.Values.globex.git.manifestFile }}"
  - name: manifestFileProd
    value: "{{ $.Values.globex.git.manifestFileProd }}"
  - name: manifestRepoName
    value: "{{ $.Values.globex.git.manifestRepoName }}"
  - name: tlsVerify
    value: "true"
  - name: gitRepoHost
    value: "{{ $.Values.globex.git.gitRepoHost }}"
  - name: sonarqubeHostUrl
    value: "{{ $.Values.globex.sonarqube.hostUrl }}"
  - name: cyclonedxHostUrl
    value: "{{ $.Values.globex.cyclonedx.hostUrl }}"
  - name: cosignPrivateKey
    value: "{{ $.Values.globex.cosign.privateKey }}"
  - name: cosignPassword
    value: "{{ $.Values.globex.cosign.password }}"
  - name: cosignPublicKey
    value: "{{ $.Values.globex.cosign.publicKey }}"