apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-sbom
spec:
  steps:
    - image: cyclonedx/cyclonedx-node
      name: test
      resources:
       requests:
         memory: 1Gi
      script: >
        apk add git jq

        npm install .

        /usr/src/cyclonedx-bom/bin/make-bom.js -o bom.json

        cat bom.json | jq
      workingDir: /workspace/repository
  workspaces:
  - name: repository