apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-directory
spec:
  description: >-
    Simple directory lister
  params:
    - name: sub-dirs
      type: array
      description: the sub-directories under workspace
      default: ['.']
  workspaces:
    - name: output
  results:
    - name: README
      description: echo the README of the repo
  steps:
    - name: list-directory
      image: busybox
      command:
        - ls
      args:
        - -ltr
        - '$(params.sub-dirs)'
      workingDir: '$(workspaces.output.path)'
    - name: show-readme
      image: busybox
      script: |
        #!/bin/sh
        [[ -f $(workspaces.output.path)/README.md ]] && cat $(workspaces.output.path)/README.md | tee /tekton/results/README && exit 0
        [[ -f $(workspaces.output.path)/README.adoc ]] && cat $(workspaces.output.path)/README.adoc | tee /tekton/results/README && exit 0