apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-sbom
spec:
  steps:
    - image: cyclonedx/cyclonedx-node
      name: test
      resources: {}
      script: >
        apk add git libxml2-utils

        cp -r /workspace/repository /tmp/repository

        cd /tmp/repository

        npm install .

        /usr/src/cyclonedx-bom/bin/make-bom.js -o bom.xml

        xmllint bom.xml
      workingDir: /workspace/repository
  workspaces:
  - name: repository